# Generated by Django 5.2.17 on 2026-08-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='api_key',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
