# Generated by Django 5.2.17 on 2026-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fallback_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agent',
            name='is_fallback',
            field=models.BooleanField(default=False),
        ),
    ]
