# Generated by Django 5.2.17 on 2026-08-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_fallback_order_agent_is_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='base_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('ollama', 'Ollama (local)'), ('openrouter', 'OpenRouter'), ('custom', 'OpenAI-compatible (base_url)')], default='openai', max_length=20),
        ),
    ]
